### ISSUE TITLE
Implement `OnchainReceive` handler 

### ISSUE THREAD

**Issue by saidalaoui-sq** [tnull/ldk-node-hack-server#26]
Implement `OnchainReceive` handler to return a new on-chain funding address

**Comment by saidalaoui-sq** [comment]
![](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExcmMyMGJmaGt2MTZjdmpleHNqZmZpbzZ0aTd0anJhb3drbDJpZWVkNyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/VHOF8pfPZOt9p018zw/giphy.gif)

**Comment by jkczyz** [comment]
Sorry, I clumped this with #6 and implemented it already in #27.

**Comment by saidalaoui-sq** [comment]
> Sorry, I clumped this with #6 and implemented it already in #27.

Np! Closing

**Comment by saidalaoui-sq** [comment]
Actually I will just repurpose the PR to include the CLI changes and rebase once your PR is merged
